# Copy this file to 'config.toml'
# You will need to make an app at https://developer.spotify.com/dashboard

username = "spotify username"
client_id = "spotify client id"
client_secret = "spotify client secret"
redirect_uri = "localhost:8000"